"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
"""

from collections import Counter

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s_cnt = Counter(s)
        for ch in t:
            if not s_cnt.get(ch):
                return ch
            else:
                s_cnt[ch] -= 1
        return '
